id: PED98E392
initial_creation_type: input
source_metadata:
  title: Ngöndro Commentary by Chökyi Drakpa
  language: bo
  description: 'The commentary on the preliminary practices of Longchen Nyingtik by
    Chökyi Drakpa (chos kyi grags pa):'
  volume:
    6d65d3f9bb994619a3a03df87320694b:
      title: 'A Torch for the Path to Omniscience: A Word by Word Commentary to the
        Longchen Nyingtik Ngöndro'
      parent: null
created_at: '2022-02-28T22:48:13.461393'
last_modified_at: '2022-02-28T22:48:13.461396'
statistics:
  total_words: 17905
  total_non_words: 1741
quality:
  non_words_ratio: 0.1
